/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EssaysRouteImport } from './routes/essays'
import { Route as MemosRouteImport } from './routes/memos'
import { Route as TechnicalEssaysRouteImport } from './routes/technical-essays'
import { Route as WritingsSlugRouteImport } from './routes/writings.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EssaysRoute = EssaysRouteImport.update({
  id: '/essays',
  path: '/essays',
  getParentRoute: () => rootRouteImport,
} as any)
const MemosRoute = MemosRouteImport.update({
  id: '/memos',
  path: '/memos',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicalEssaysRoute = TechnicalEssaysRouteImport.update({
  id: '/technical-essays',
  path: '/technical-essays',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingsSlugRoute = WritingsSlugRouteImport.update({
  id: '/writings/$slug',
  path: '/writings/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/essays': typeof EssaysRoute
  '/memos': typeof MemosRoute
  '/technical-essays': typeof TechnicalEssaysRoute
  '/writings/$slug': typeof WritingsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/essays': typeof EssaysRoute
  '/memos': typeof MemosRoute
  '/technical-essays': typeof TechnicalEssaysRoute
  '/writings/$slug': typeof WritingsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/essays': typeof EssaysRoute
  '/memos': typeof MemosRoute
  '/technical-essays': typeof TechnicalEssaysRoute
  '/writings/$slug': typeof WritingsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/essays' | '/memos' | '/technical-essays' | '/writings/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/essays' | '/memos' | '/technical-essays' | '/writings/$slug'
  id:
    | '__root__'
    | '/'
    | '/essays'
    | '/memos'
    | '/technical-essays'
    | '/writings/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EssaysRoute: typeof EssaysRoute
  MemosRoute: typeof MemosRoute
  TechnicalEssaysRoute: typeof TechnicalEssaysRoute
  WritingsSlugRoute: typeof WritingsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/essays': {
      id: '/essays'
      path: '/essays'
      fullPath: '/essays'
      preLoaderRoute: typeof EssaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memos': {
      id: '/memos'
      path: '/memos'
      fullPath: '/memos'
      preLoaderRoute: typeof MemosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technical-essays': {
      id: '/technical-essays'
      path: '/technical-essays'
      fullPath: '/technical-essays'
      preLoaderRoute: typeof TechnicalEssaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writings/$slug': {
      id: '/writings/$slug'
      path: '/writings/$slug'
      fullPath: '/writings/$slug'
      preLoaderRoute: typeof WritingsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EssaysRoute: EssaysRoute,
  MemosRoute: MemosRoute,
  TechnicalEssaysRoute: TechnicalEssaysRoute,
  WritingsSlugRoute: WritingsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
